default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: broker_free_db
production:
  <<: *default
  database: broker_free_db
  username: postgres
  password: postgres
test:
  <<: *default
  database: test_broker_free_db
